In [ ]:
pip install yfinance

Holts winter model

In [ ]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
a=yf.download('ASTRAL.NS',start='2000-01-01',interval='1d')

[*********************100%***********************]  1 of 1 completed


In [ ]:
a=a['Adj Close']

In [ ]:
a=a.to_list()

In [ ]:
a

In [ ]:
len(a)

3582

In [ ]:
type(a)

list

In [ ]:
l=[]
b=[]
b12=[]
l.append(a[0])
b.append(0)
b12.append(0)
f=[]
f.append(0)
f123=[]
f123.append(0)


In [ ]:
l.append(al*y[i]+(1-al)*(l[i-1]+b[i-1])
b.append(bl*(l[i]-l[i-1])+(1-bl)*b[i-1])
f.append(l[i]+b[i])

In [ ]:
rsm=0
abc=[]
abcd=[]

In [ ]:
num_ports = 10000
rsme=[]
for ind in range(num_ports):
  w12 = np.array(np.random.random(2))
  abc.append([w12])

In [ ]:
b123=[]

In [ ]:
num_ports = 10000
rsme=[]
for ind in range(num_ports):
  w12 = np.array(np.random.random(1))
  w11 = np.array(np.random.random(1))
  abc.append(w12)
  abcd.append(w11)
  for i in range(1,len(a)):
    qw=(w12*a[i]+(1-w12)*(l[i-1]+b[i-1]))
    l.append(qw)
    b1=(w12*(l[i]-l[i-1])+(1-w12)*b[i-1])
    b.append(b1)
    f12=qw+b1
    rsm=rsm+(f12-a[i])*(f12-a[i])
  rs1=(rsm/(len(a)-1))**2
  rsme.append(rs1)
  rsm=0   
alpha=abc[rsme.index(min(rsme))]
beta=abcd[rsme.index(min(rsme))]
for i in range(1,len(a)):
  qw=(alpha*a[i]+(1-alpha)*(l[i-1]+b[i-1]))
  b1=(beta*(l[i]-l[i-1])+(1-beta)*b[i-1])
  b123.append(b1)
  f12=qw+b1
  f123.append(f12)


In [ ]:
b1

array([12.74254823])

In [ ]:
ab12=sum(b123)/len(b123)

In [ ]:
ab12

array([0.62484301])

In [ ]:
len(b123)

3581

In [ ]:
qw

array([2236.53025498])

In [ ]:
(beta*(l[i]-l[i-1])+(1-beta)*b[i-1])

array([-27.88303695])

In [ ]:
b[i-1]

array([-48.71847263])

In [ ]:
b1

array([-27.88303695])

In [ ]:
abcd

In [ ]:
print('prediction price of the stock after one year')
print(qw+ab12*250)

prediction price of the stock after one year
[2390.51789302]
